name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  unit-test:
    needs: lint-test
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python and pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run unit tests
        run: pytest tools.py --doctest-modules

  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install flake8
        run: pip install flake8
      - name: Run lint tests
        run: flake8 app.py

  git-setting-zip:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure git user
        run: |
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER_NAME }}"
      - name: Create release branch
        run: |
          git checkout -b "release-$(date +"%Y-%m-%d")"
          git push -u origin "release-$(date +"%Y-%m-%d")"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'
      - name: Zip files
        run: |
          pip install zip_files
          python zip.py
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER_NAME }}"
          git add .
          git commit -m "ajout de l'archive"
          git push

  code-coverage:
    needs: git-setting-zip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'
      - name: coverage
        run: |
          git checkout "release-$(date +"%Y-%m-%d")"
          pip install pytest-cov
          pip install coverage-badge
          pytest --cov=. . --doctest-modules --ignore=app.py
          coverage-badge >> readme.md
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER_NAME }}"
          git add .
          git commit -m "ajout du badge de couverture dans le readme.md"
          git push
          
  deploy:
    needs: code-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        run: echo "ready to deploy"

  message:
    runs-on: ubuntu-latest
    if: always()
    needs: deploy
    steps:
      - name: Send message
        run: echo "pipeline launched"